### ISSUE TITLE
Rework "Validators/Eth1 Deposits"

### ISSUE THREAD

**Issue by akolotov** [canarynetwork/eth2-beaconchain-explorer#10]
Rename the menu item "Validators/Eth1 Deposits" to "Validators/Deposits on xDai"

Make the label on "Validators/Eth1 Deposits" configurable as so

- "Eth1 deposits leaderboard" can be replaced by "xDai deposits leaderboard"
- "Eth1 Address" can be replaced by "xDai addresses"
- Staking token symbol ETH can be replaced by "STAKE"

![image](https://user-images.githubusercontent.com/20793260/128564619-94e2f3a7-cd1a-4bb2-8fc9-3a2f606a4d01.png)

**Comment by akolotov** [comment]
Addressed by #29

**Comment by rimrakhimov** [comment]
I believe this issue was not completely addressed by #29. The only thing the branch did was replacing staking token symbol from "ETH" to "STAKE" by making the symbol configurable. "Eth1" labels were not addressed by the request.

Additionally, I am not sure, but isn't this issue more connected to the "Validators/Deposit Leaderboard" menu item (`u.r.l./validators/eth1leaderboard`)? 

Because the "Validators/Eth1 Deposits" menu item shows another information:
![image](https://user-images.githubusercontent.com/25086020/135718266-88ef0a13-21be-4c36-86fe-e7ae5c80c0a5.png)
